name: Generate Airplane Game

on:
  schedule:
    - cron: "0 */12 * * *" # runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repo
      - uses: actions/checkout@v3

      # Generate the animation (default snake, can be customized)
      - uses: Platane/snk@master
        with:
          github_user_name: Iamnehal0
          outputs: dist/airplane.svg

      # Commit the generated file back to your repo
      - name: Push Airplane
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate Airplane Game"
          add: "dist/*"
